# Generated by Django 5.2.2 on 2025-06-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord'), ('manager', 'Property Manager')], default='tenant', help_text='Designates the role of the user in the system.', max_length=20),
        ),
    ]
