# Generated by Django 5.2.2 on 2025-06-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
        migrations.AlterField(
            model_name='property',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='property_photos/'),
        ),
    ]
