# Generated by Django 5.2.2 on 2025-06-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_name_alter_property_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='lease_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='lease_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
