# Generated by Django 5.2.2 on 2025-06-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_photo_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
